### ISSUE TITLE
Basic Logo

### ISSUE THREAD

**Issue by ohld** [testnet-exchange/frontend#6]
Нам нужно квадратное лого. Хочется простое, чтобы было мало деталей.

**Comment by 0xZick** [comment]
![2](https://user-images.githubusercontent.com/17093843/44190263-95e23e80-a12e-11e8-9602-66060ed8a408.png)

**Comment by ohld** [comment]
![combined shape](https://user-images.githubusercontent.com/5613295/44204103-05b9ee80-a15a-11e8-994f-4645b098bacd.png)

**Comment by ohld** [comment]
Good job on this issue!
